---
title: "Contributing to prioriactions"
output:
  rmarkdown::github_document:
    html_preview: no
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
devtools::load_all()
```
First of all, thanks for considering contributing to prioriactions!. We greatly appreciate your interest in improving and expanding the package. All people are very much welcome to contribute to code, documentation, testing and suggestions.

[repo]: https://github.com/prioriactions/prioriactions
[issues]: https://github.com/prioriactions/prioriactions/issues
[new_issue]: https://github.com/prioriactions/prioriactions/issues/new
[website]: https://prioriactions.net

## How you can contribute

There are several ways you can contribute to this project. We welcome and encourage contributions from all members of the community.

## Share

Think prioriactions is useful? Let others discover it by telling them in person, via Twitter, or writing a blog post about it. If you are using prioriactions for a research paper, consider citing it to acknowledge the contribution.

## Ask a question

Using prioriactions and got stuck? Browse the documentation to see if you can find a solution. Still stuck? Post your question as an issue on GitHub. While we cannot offer user support, we'll try our best to address it, as questions often lead to better documentation or the discovery of bugs.

If you want to ask a question in private, you can contact the package maintainer by emailing email.

Propose an idea 💡
Have an idea for a new feature in prioriactions? Take a look at the documentation and issue list to see if it isn't already included or suggested. If not, suggest your idea as an issue on GitHub. While we can't promise to implement every idea, it certainly helps to:

Explain in detail how your proposed feature would work.
Keep the scope as narrow as possible to ensure feasibility.
See below if you want to contribute code for your idea as well.

Report a bug 🐛
Discovered a bug while using prioriactions? That's unfortunate! Please don't let others have the same experience and report it as an issue on GitHub so we can fix it. A good bug report makes it easier for us to address the problem, so please include the following details:

Your operating system name and version (e.g., Mac OS 10.13.6).
Any details about your local setup that might be helpful in troubleshooting.
Detailed steps to reproduce the bug.
Improve the documentation 📚
Noticed a typo on the website? Think a function could use a better example? High-quality documentation makes all the difference, so your help in improving it is very welcome!

The website
The prioriactions website is generated with pkgdown. That means we don't have to write any HTML: the content is pulled together from documentation in the code, vignettes, Markdown files, the package DESCRIPTION, and _pkgdown.yml settings. If you know your way around pkgdown, you can propose a file change to improve the documentation. If not, report an issue, and we can point you in the right direction.

Function documentation
Functions in prioriactions are described as comments near their code and are translated to documentation using roxygen2. If you want to improve a function's description:

Go to the R/ directory in the code repository.
Look for the file with the name of the function.
Propose a file change to update the function documentation in the roxygen comments (starting with #').
Contribute code 📝
If you'd like to fix bugs or implement new functionality for prioriactions, that's awesome! 👏 Here's how you can get started:

Have a look at the issue list and leave a comment on the things you want to work on.
Fork this repository and clone it to your computer. If you're not familiar with this process, see this guide for more information.
If you've forked and cloned the project before and it has been a while since you worked on it, pull changes from the original repository to your clone by using git pull upstream master.
Open the RStudio project file (.Rproj).
Make your changes:
Write your code.
Test your code (bonus points for adding unit tests).
Document your code (see function documentation above).
Check your code with devtools::check() and aim for 0 errors and warnings.
Commit and push your changes.
Submit a pull request.
Development guidelines
We try to follow the GitHub flow for development, and we appreciate your adherence to these guidelines when contributing.

Your contributions are valuable to the growth and improvement of prioriactions. Thank you for taking the time to make this project even better! 🙏 If you have any questions, feel free to reach out to us through the issues or by contacting the package maintainer via email.
