---
title: "Prueba amount con Mitchell"
author: "jose"
date: "5/26/2021"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Instalación y carga

Instalamos la versión de desarrollo del paquete.

```{r eval=FALSE}
if (!require(devtools)) install.packages("devtools")
devtools::install_github("josesalgr/prioriactions", ref = "develop")
```

Cargamos librerías

```{r eval=FALSE}
library(prioriactions)
library(raster) #Para plotear el shapefile
library(viridis) #Colores
```

Cargamos inputs que vienen como parte de la instalación del paquete (dado que los usamos en una viñeta)

```{r echo=TRUE}
## path donde se instala vuestro paquete
path <- system.file("extdata/input_big/", package = "prioriactions")

pu_data <- data.table::fread(paste0(path,"unitCost_Big.csv"), data.table = FALSE)
features_data <- data.table::fread(paste0(path,"target_Big.csv"), data.table = FALSE)
rij_data <- data.table::fread(paste0(path,"speciesDistribution_Big.csv"), data.table = FALSE)
bound_data <- data.table::fread(paste0(path,"boundary_Big.csv"), data.table = FALSE)
threats_data <- data.table::fread(paste0(path,"threatsDistribution_Big.csv"), data.table = FALSE)
sensitivity_data <- data.table::fread(paste0(path,"sensibility_Big.csv"), data.table = FALSE)
```

Carga del shapefile

```{r eval=FALSE}
#reading shapefile
shp_mitchell = shapefile(paste0(path,"Fish_Mitchell.shp"))
```

## Modelo básico con especies 
