# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcpp_new_optimization_problem <- function(nrow = 1000000L, ncol = 1000000L, ncell = 100000L) {
    .Call(`_prioriactions_rcpp_new_optimization_problem`, nrow, ncol, ncell)
}

rcpp_optimization_problem_as_list <- function(x) {
    .Call(`_prioriactions_rcpp_optimization_problem_as_list`, x)
}

rcpp_get_optimization_problem_ncol <- function(x) {
    .Call(`_prioriactions_rcpp_get_optimization_problem_ncol`, x)
}

rcpp_get_optimization_problem_nrow <- function(x) {
    .Call(`_prioriactions_rcpp_get_optimization_problem_nrow`, x)
}

rcpp_get_optimization_problem_ncell <- function(x) {
    .Call(`_prioriactions_rcpp_get_optimization_problem_ncell`, x)
}

rcpp_get_optimization_problem_A <- function(x) {
    .Call(`_prioriactions_rcpp_get_optimization_problem_A`, x)
}

rcpp_constraint_activation <- function(x, pu_data, threats_data, dist_threats_data) {
    .Call(`_prioriactions_rcpp_constraint_activation`, x, pu_data, threats_data, dist_threats_data)
}

rcpp_constraint_benefit <- function(x, pu_data, features_data, dist_features_data, threats_data, dist_threats_data, sensitivity_data) {
    .Call(`_prioriactions_rcpp_constraint_benefit`, x, pu_data, features_data, dist_features_data, threats_data, dist_threats_data, sensitivity_data)
}

rcpp_constraint_budget <- function(x, pu_data, dist_threats_data, budget) {
    .Call(`_prioriactions_rcpp_constraint_budget`, x, pu_data, dist_threats_data, budget)
}

rcpp_constraint_lock <- function(x, pu_data, dist_threats_data) {
    .Call(`_prioriactions_rcpp_constraint_lock`, x, pu_data, dist_threats_data)
}

rcpp_constraint_target <- function(x, pu_data, features_data, dist_features_data, dist_threats_data, threats_data, sensitivity_data, curve) {
    .Call(`_prioriactions_rcpp_constraint_target`, x, pu_data, features_data, dist_features_data, dist_threats_data, threats_data, sensitivity_data, curve)
}

rcpp_objective_max_coverage <- function(x, pu_data, features_data, dist_features_data, threats_data, dist_threats_data, boundary_data, blm, curve) {
    .Call(`_prioriactions_rcpp_objective_max_coverage`, x, pu_data, features_data, dist_features_data, threats_data, dist_threats_data, boundary_data, blm, curve)
}

rcpp_objective_min_set <- function(x, pu_data, features_data, dist_features_data, threats_data, dist_threats_data, boundary_data, blm, curve) {
    .Call(`_prioriactions_rcpp_objective_min_set`, x, pu_data, features_data, dist_features_data, threats_data, dist_threats_data, boundary_data, blm, curve)
}

rcpp_stats_benefit <- function(pu_data, features_data, dist_features_data, threats_data, dist_threats_data, sensitivity_data, solution) {
    .Call(`_prioriactions_rcpp_stats_benefit`, pu_data, features_data, dist_features_data, threats_data, dist_threats_data, sensitivity_data, solution)
}

rcpp_stats_connectivity_actions <- function(pu_data, threats_data, dist_threats_data, boundary_data, solution) {
    .Call(`_prioriactions_rcpp_stats_connectivity_actions`, pu_data, threats_data, dist_threats_data, boundary_data, solution)
}

rcpp_stats_connectivity_units <- function(pu_data, boundary_data, dist_threats_data, dist_features_data, solution) {
    .Call(`_prioriactions_rcpp_stats_connectivity_units`, pu_data, boundary_data, dist_threats_data, dist_features_data, solution)
}

rcpp_stats_costs_actions <- function(pu_data, threats_data, dist_threats_data, solution) {
    .Call(`_prioriactions_rcpp_stats_costs_actions`, pu_data, threats_data, dist_threats_data, solution)
}

rcpp_stats_costs_units <- function(pu_data, solution) {
    .Call(`_prioriactions_rcpp_stats_costs_units`, pu_data, solution)
}

rcpp_stats_recovery <- function(solution, pu_data, features_data, dist_features_data, dist_threats_data, threats_data, sensitivity_data) {
    .Call(`_prioriactions_rcpp_stats_recovery`, solution, pu_data, features_data, dist_features_data, dist_threats_data, threats_data, sensitivity_data)
}

